### ISSUE TITLE
[Warning]: New change to Xbox policy starting on November 12 could possibly affect the new firmware of Guitar Configurator

### ISSUE THREAD

**Issue by ghost** [Santroller/guitar-configurator#10]
### Please describe your issue.

Although not an issue, Microsoft has just announced that a new update to the Xbox One and Series consoles that will prohibit any form of unlicensed or unauthorized third party accessories, which may include anything using Guitar Configurator (such as the RetroCultMods V3 Wii adapter), which will come into effect on November 12th. I would suggest testing out the adapter with the new firmware on November 12th to ensure that everything is in working order, and if more work needs to be done if affected. Here is a link to the article: https://www.windowscentral.com/gaming/xbox/xboxs-new-policy-say-goodbye-to-unofficial-accessories-after-november

### Version

yes

### What operating system are you using?

Other

### os-other

Xbox consoles, particular Xbox One and Series

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
Nah this doesn't affect us, we pass through auth from first party conttollers

**Comment by ghost** [comment]
Cool, just wanted to ensure that y'all weren't affected. Glad to hear.
