### ISSUE TITLE
[Request]: Add more instructions for RF using Pi Pico

### ISSUE THREAD

**Issue by Zepherian04** [Santroller/guitar-configurator#11]
### Please describe your request.

I see there are pins specified for the Arduino boards when creating a wireless guitar, are there specifics for doing this with a pi pico?

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
RF support is going to be killed. It will be replaced with pi pico w based wireless in the future.

**Comment by sanjay900** [comment]
Ive just pushed the documentation changes to make it clear that RF isnt something you should be working with anymore.
