### ISSUE TITLE
[Issue]: Unable to connect to xbox

### ISSUE THREAD

**Issue by Minix07** [Santroller/guitar-configurator#12]
### Please describe your issue.

I'm using Retro cult modding's V3 Wii Adapter for my wii and have configured it to output as a Xbox gamepad and didn't work.
I tried using the USB port at the top to connect to a first party controller and it didn't work.

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by ghost** [comment]
@Minix07 Sanjay has confirmed that Xbox support will be included on the next firmware update, so please stay updated on that.

**Comment by sanjay900** [comment]
For now, you need to mod your 360 to use the adapter. That USB port doesn't currently do anything, and won't until the new firmware is released.

**Comment by sanjay900** [comment]
Also, for future reference, if you are having problems with an adapter, contact the seller, not the project, they can provide better support that i will be able to.

**Comment by Minix07** [comment]
Will this new firmware add support to Xbox one or will the Xbox 360 option work with an Xbox one?

**Comment by sanjay900** [comment]
Its just totally different in how it functions, when it comes out all your questions will be answered by new documentation.
