### ISSUE TITLE
Pi pico works for 1min and stop working

### ISSUE THREAD

**Issue by LitZ157** [Santroller/guitar-configurator#14]
### Please describe your issue.

First, congrats for your job 
I'm having a little problem, when i connect to the wii guitar everything work for like 30/40 seconds and stop working, if i unplug and plug again work for another 30/40 seconds, you have any idea what is the problem ? I try diferent cables and its the same thing.
Thanks again man :)

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
normally that sort of thing is a wiring problem

**Comment by LitZ157** [comment]
I will try soldering everything again and buy another usb cable, i give you updates, thanks man :p

**Comment by LitZ157** [comment]
Update here its solved, it was my bad i don't know why but i put 1 wire in to the wrong place while seeing the tutorial.
Thanks again and sorry for wasting your time 
Cheers

**Comment by sanjay900** [comment]
Good to hear that you got it solved!
