### ISSUE TITLE
Adapt back to ps2

### ISSUE THREAD

**Issue by kizzoknight** [Santroller/guitar-configurator#18]
### Please describe your request.

Add the ability or guide to adapt a usb controller using a pi Pico or Arduino back to ps2 so you can use on PS2 if possible 

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

PS2

**Comment by sanjay900** [comment]
Not something i'm all that interested in doing. You can use PADEMU if you need it to work on a PS2.
PADEMU supports emulating both standard pads and guitars.

Everything is very tightly bound around USB, so it would involve a lot of changes to the core codebase, and thus its not something I want to implement.
