### ISSUE TITLE
[Issue]:  Can't install Guitar Configurator on Windows 11 latest version. 

### ISSUE THREAD

**Issue by MalikATL** [Santroller/guitar-configurator#19]
### Please describe your issue.

 updated to the latest version of windows 11 and now Guitar Configurator won't install or open 

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
No idea what would cause that, have you tried uninstalling and reinstalling it?

**Comment by ParanoiAgent** [comment]
I just encounter this issue downloading for the first time. It would download in chrome but wouldn't run the installer. Here's what I did. In chrome download link, click on downloads tab, click show in folder, right click program, run as administrator when the window for defender pops up click the show options link then click run anyway, and it should install and run as normal. Hope this helps.

**Comment by sanjay900** [comment]
@MalikATL did this work for you?

**Comment by MalikATL** [comment]
> @MalikATL did this work for you?

yeah it did
