### ISSUE TITLE
[Issue]: LEDs not assigning correctly with PolyPCB v1.2

### ISSUE THREAD

**Issue by HankChill** [Santroller/guitar-configurator#2]
### Please describe your issue.

A few weeks ago, the Polybar folks released an updated version of their PCB, which includes additional LEDs for Start, Select, as well as dual LEDs for the fret PCB that flank each of the mechanical switches. When assigning the LEDs to the different pins, pressing the corresponding button ends up lighting up different LEDs on the board. The correct button is registering as I've tested it in Clone Hero, but the LEDs do not correspond to the button pressed. The only ones which light up correctly are Start and Select.

My configuration in the Guitar Configurator also appears to be correct as I don't see any other way to configure how LEDs are assigned to the different buttons.

![image](https://github.com/sanjay900/guitar-configurator/assets/40478741/aa015652-5834-4198-8543-0e1b0494e8f4)

I've also created a video to show how the lights seem to not register to the correct buttons.

https://photos.app.goo.gl/pnVBuGZdJ1JwdxM67

I'm hoping this is not an issue with their updated PCBs, but since I'm able to get all the lights to light up (albeit the wrong lights), I'm also hoping that the issue can be corrected on the software end.

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Did you hit configure leds and then drag the leds around to put them in the right order?
I intend to make this a bit more obvious in the future, but that "Configure LEDs" dialog should give you the ability to reorder the leds.
This version of the tool won't support dual LEDs though, but one being worked on will.

**Comment by HankChill** [comment]
That was exactly what I was missing! :)

I didn't quite understand that section and didn't realize that dragging around the LED indicators was actually corresponding to a button press -- after a little bit of trial and error, I was able to successfully configure the LEDs to the appropriate button presses.

Thanks for your awesome work!
