### ISSUE TITLE
wiitar bug

### ISSUE THREAD

**Issue by TTV-Vicho** [Santroller/guitar-configurator#6]
### Please describe your issue.

when i flash my pi pico and try it on my wiitar it detects it as keyboard and mouse + gamepad and it's really annoying because I can't navigate well with my mouse

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
If it's controlling your mouse, that's a steam bug. Close steam or disable
Xbox 360 controller support within steam.
The mouse and keyboard that show up don't actually matter or do anything, there's a steam feature where it will let you control the mouse with a controller and that just seems to go haywire for some people.
Hopefully when the new firmware is released this won't be an actual issue anymore, but i have zero clue what actually causes it, it is not the mouse and keyboard showing up.

**Comment by TTV-Vicho** [comment]
i think that's a problem from windows because my friend had a xbox series controller and the same thing occurs, control a kb+m for navigation on windows
