### ISSUE TITLE
[Request]: Minimum button press threshold proposal 

### ISSUE THREAD

**Issue by archwk100** [Santroller/guitar-configurator#7]
### Please describe your request.

I have a proposal for a feature that could allow players to play on a high poll rate or even queued inputs, without the downside of the smallest input of a button triggering a button press, making the player ghost and break combo. The proposal would be to have a roughly 1-2ms delay between when the inputs are received and when the inputs are output to the computer, allowing for the guitar to negate all button presses shorter than that 1-2ms delay. I don't think 5 fret games require extreme low latency down to the millisecond, and this feature could potentially make playing anti-ghost engines much easier by allowing for thousands of hertz poll rate, while also negating accidental button presses that are <1-2ms in duration.

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
I guess i can see how this might work, but it isnt something ill implement any time soon.
Its sort of like a inverse debounce, where instead of lengthening a short button press, your just discarding it entirely.

**Comment by archwk100** [comment]
Yep it would discard any short button presses. This is a very large problem when playing anti ghost because when tapping its extremely easier to accidently trigger a ~1-2 ms button press due to the way guitars are designed.
This doesn't apply much to casuals, but now that top players are trying to push the skill ceiling of YARG no ghost, this could potentially be the new meta for how inputs are handled. Really hope you can get around to implementing this at some point.

**Comment by sanjay900** [comment]
Yeah, at the moment im tied up in trying to finish things for the new firmware release, but once thats done then i can try implementing this

**Comment by sanjay900** [comment]
Weird request, but could you re-raise this one under https://github.com/Santroller/Santroller ? 
This repo will be archived when the new firmware is released and i don't want to lose this,
And new firmware stuff is happening under that repo.

**Comment by archwk100** [comment]
done
