### ISSUE TITLE
[Issue]: My pi pico is freezed on this page

### ISSUE THREAD

**Issue by Psayz** [Santroller/guitar-configurator#8]
### Please describe your issue.

My pi pico not run from next page

https://prnt.sc/WqFSjZY8rYhR

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
What have you hooked up to it?

**Comment by sanjay900** [comment]
Also, download this: https://www.nirsoft.net/utils/usb_devices_view.html
Unplug the pico, run it and uninstall anything with vid 1209 pid 2882
Then plug the pico back in

Or just try another computer.

**Comment by Psayz** [comment]
ok I'll try that now

**Comment by Psayz** [comment]
ITS WORK!!!! THKS
